server:
  port: 8207
spring:
  application:
    name: service-orders
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  data:
    mongodb:
      uri: mongodb://192.168.111.100:27017/yygh_hosp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: BGK796288311
    url: jdbc:mysql://localhost:3306/yygh_order?characterEncoding=utf-8&useSSL=false
    username: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  redis:
    database: 1
    host: 192.168.111.100
    password: BGK796288311
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 1800000
