server:
  port: 8202
spring:
  application:
    name: service-cmn
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: BGK796288311
    url: jdbc:mysql://localhost:3306/yygh_cmn?characterEncoding=utf-8&useSSL=false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  redis:
    database: 1
    host: 192.168.111.100
    password: BGK796288311
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 1800000
  devtools:
    livereload:
      port: 35730
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848