server:
  port: 8201
spring:
  application:
    name: service-hosp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: BGK796288311
    url: jdbc:mysql://localhost:3306/yygh_hosp?characterEncoding=utf-8&useSSL=false
  #全局时间处理，针对controller层所有的返回json时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://192.168.111.100:27017/yygh_hosp
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  rabbitmq:
    host: 192.168.111.100
    port: 5672
    username: guest
    password: guest
    virtualHost: /

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
