server:
  port: 8206
spring:
  profiles:
    active: dev
  application:
    name: service-msm
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 1
    host: 192.168.111.100
    password: BGK796288311
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        max-wait: -1
        min-idle: 0
    port: 6379
